services:
  blazor_wasm_sqm:
    build:
      context: ./Blazor_wasm
      dockerfile: Dockerfile
    ports:
      - "88:80"
    volumes:
      - ./publish/wwwroot:/usr/share/nginx/html:ro
    restart: always