//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor_wasm.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor_wasm.Resources.Languages.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Already have account 的當地語系化字串。
        /// </summary>
        internal static string account_already_account {
            get {
                return ResourceManager.GetString("account_already_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back to login 的當地語系化字串。
        /// </summary>
        internal static string account_back_login {
            get {
                return ResourceManager.GetString("account_back_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create a new account 的當地語系化字串。
        /// </summary>
        internal static string account_create_account {
            get {
                return ResourceManager.GetString("account_create_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete Account 的當地語系化字串。
        /// </summary>
        internal static string account_delete_account {
            get {
                return ResourceManager.GetString("account_delete_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Email Address 的當地語系化字串。
        /// </summary>
        internal static string account_email_address {
            get {
                return ResourceManager.GetString("account_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter your email address 的當地語系化字串。
        /// </summary>
        internal static string account_ent_email_address {
            get {
                return ResourceManager.GetString("account_ent_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter the first name 的當地語系化字串。
        /// </summary>
        internal static string account_ent_first_name {
            get {
                return ResourceManager.GetString("account_ent_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter the last name 的當地語系化字串。
        /// </summary>
        internal static string account_ent_last_name {
            get {
                return ResourceManager.GetString("account_ent_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter the new password 的當地語系化字串。
        /// </summary>
        internal static string account_ent_new_password {
            get {
                return ResourceManager.GetString("account_ent_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter your old password 的當地語系化字串。
        /// </summary>
        internal static string account_ent_old_password {
            get {
                return ResourceManager.GetString("account_ent_old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter your password 的當地語系化字串。
        /// </summary>
        internal static string account_ent_password {
            get {
                return ResourceManager.GetString("account_ent_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter the verification code 的當地語系化字串。
        /// </summary>
        internal static string account_ent_verification_code {
            get {
                return ResourceManager.GetString("account_ent_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 First Name 的當地語系化字串。
        /// </summary>
        internal static string account_first_name {
            get {
                return ResourceManager.GetString("account_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Forgot the password 的當地語系化字串。
        /// </summary>
        internal static string account_forgot_password {
            get {
                return ResourceManager.GetString("account_forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Last Name 的當地語系化字串。
        /// </summary>
        internal static string account_last_name {
            get {
                return ResourceManager.GetString("account_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login 的當地語系化字串。
        /// </summary>
        internal static string account_login {
            get {
                return ResourceManager.GetString("account_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Logout 的當地語系化字串。
        /// </summary>
        internal static string account_logout {
            get {
                return ResourceManager.GetString("account_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Modify Account 的當地語系化字串。
        /// </summary>
        internal static string account_modify_account {
            get {
                return ResourceManager.GetString("account_modify_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New Password 的當地語系化字串。
        /// </summary>
        internal static string account_new_password {
            get {
                return ResourceManager.GetString("account_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Old Password 的當地語系化字串。
        /// </summary>
        internal static string account_old_password {
            get {
                return ResourceManager.GetString("account_old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        internal static string account_password {
            get {
                return ResourceManager.GetString("account_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter the password again 的當地語系化字串。
        /// </summary>
        internal static string account_password_again {
            get {
                return ResourceManager.GetString("account_password_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Registration 的當地語系化字串。
        /// </summary>
        internal static string account_registration {
            get {
                return ResourceManager.GetString("account_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset Password 的當地語系化字串。
        /// </summary>
        internal static string account_reset_password {
            get {
                return ResourceManager.GetString("account_reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select the account 的當地語系化字串。
        /// </summary>
        internal static string account_select_account {
            get {
                return ResourceManager.GetString("account_select_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Submit 的當地語系化字串。
        /// </summary>
        internal static string account_submit {
            get {
                return ResourceManager.GetString("account_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 In Alarm 的當地語系化字串。
        /// </summary>
        internal static string alarm_active {
            get {
                return ResourceManager.GetString("alarm_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acid level too low 的當地語系化字串。
        /// </summary>
        internal static string alarm_common0 {
            get {
                return ResourceManager.GetString("alarm_common0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Buf.A liquid level is too low 的當地語系化字串。
        /// </summary>
        internal static string alarm_common1 {
            get {
                return ResourceManager.GetString("alarm_common1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Buf.B liquid level is too low 的當地語系化字串。
        /// </summary>
        internal static string alarm_common2 {
            get {
                return ResourceManager.GetString("alarm_common2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Abnormal air pressure 的當地語系化字串。
        /// </summary>
        internal static string alarm_common3 {
            get {
                return ResourceManager.GetString("alarm_common3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Overcurrent 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver1 {
            get {
                return ResourceManager.GetString("alarm_driver1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder Vibration Warning 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver100 {
            get {
                return ResourceManager.GetString("alarm_driver100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Absolute Position Turns Overflow_Driver 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver102 {
            get {
                return ResourceManager.GetString("alarm_driver102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder Temperature Warning 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver103 {
            get {
                return ResourceManager.GetString("alarm_driver103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Absolute data IO transmission error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver104 {
            get {
                return ResourceManager.GetString("alarm_driver104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Motor type error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver105 {
            get {
                return ResourceManager.GetString("alarm_driver105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Control power failure caused write failure 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver1058 {
            get {
                return ResourceManager.GetString("alarm_driver1058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_The error between the internal coordinates of the driver and the encoder coordinates is too large 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver107 {
            get {
                return ResourceManager.GetString("alarm_driver107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder type cannot be recognized 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver108 {
            get {
                return ResourceManager.GetString("alarm_driver108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_absolute position establishment is not completed 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver109 {
            get {
                return ResourceManager.GetString("alarm_driver109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder read and write incomplete warning 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver112 {
            get {
                return ResourceManager.GetString("alarm_driver112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder turns error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver113 {
            get {
                return ResourceManager.GetString("alarm_driver113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder Overspeed 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver114 {
            get {
                return ResourceManager.GetString("alarm_driver114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder memory error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver115 {
            get {
                return ResourceManager.GetString("alarm_driver115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder single turn absolute position error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver116 {
            get {
                return ResourceManager.GetString("alarm_driver116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder absolute number of revolutions error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver117 {
            get {
                return ResourceManager.GetString("alarm_driver117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder parameter setting is not completed error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver121 {
            get {
                return ResourceManager.GetString("alarm_driver121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder Z phase position lost 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver122 {
            get {
                return ResourceManager.GetString("alarm_driver122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder Memory Busy 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver123 {
            get {
                return ResourceManager.GetString("alarm_driver123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_When the motor speed exceeds 200rpm, clear the absolute position 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver124 {
            get {
                return ResourceManager.GetString("alarm_driver124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_The motor stops running when the power is turned on again without releasing AL07C 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver125 {
            get {
                return ResourceManager.GetString("alarm_driver125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder Clearer Error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver126 {
            get {
                return ResourceManager.GetString("alarm_driver126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder version number is abnormal 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver127 {
            get {
                return ResourceManager.GetString("alarm_driver127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Driver output current is too large 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver131 {
            get {
                return ResourceManager.GetString("alarm_driver131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Flexibility compensation parameter abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver1313 {
            get {
                return ResourceManager.GetString("alarm_driver1313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Regeneration setting abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver133 {
            get {
                return ResourceManager.GetString("alarm_driver133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Regenerative resistor overload 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver134 {
            get {
                return ResourceManager.GetString("alarm_driver134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Driver function usage alarm 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver136 {
            get {
                return ResourceManager.GetString("alarm_driver136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Current sensing is disturbed 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver137 {
            get {
                return ResourceManager.GetString("alarm_driver137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Automatic gain adjustment command abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver138 {
            get {
                return ResourceManager.GetString("alarm_driver138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Automatic gain adjustment stop time is too short 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver139 {
            get {
                return ResourceManager.GetString("alarm_driver139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Automatic gain adjustment inertia estimation abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver140 {
            get {
                return ResourceManager.GetString("alarm_driver140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_DSP firmware error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver153 {
            get {
                return ResourceManager.GetString("alarm_driver153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Parameter reset failed 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver156 {
            get {
                return ResourceManager.GetString("alarm_driver156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Capacitor charging abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver157 {
            get {
                return ResourceManager.GetString("alarm_driver157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Abnormal voltage in regeneration state 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver16 {
            get {
                return ResourceManager.GetString("alarm_driver16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_The absolute position coordinates of the driver and the motor do not match 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver166 {
            get {
                return ResourceManager.GetString("alarm_driver166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_CN2 communication failed 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver17 {
            get {
                return ResourceManager.GetString("alarm_driver17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Emergency Stop 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver19 {
            get {
                return ResourceManager.GetString("alarm_driver19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Overvoltage 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver2 {
            get {
                return ResourceManager.GetString("alarm_driver2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Reverse limit abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver20 {
            get {
                return ResourceManager.GetString("alarm_driver20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Forward limit abnormal 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver21 {
            get {
                return ResourceManager.GetString("alarm_driver21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_IGBT temperature abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver22 {
            get {
                return ResourceManager.GetString("alarm_driver22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Memory Abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver23 {
            get {
                return ResourceManager.GetString("alarm_driver23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_OA and OB output abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver24 {
            get {
                return ResourceManager.GetString("alarm_driver24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Low Voltage 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver3 {
            get {
                return ResourceManager.GetString("alarm_driver3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_ Motor power line disconnection detection 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver3121 {
            get {
                return ResourceManager.GetString("alarm_driver3121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Serial communication timeout 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver32 {
            get {
                return ResourceManager.GetString("alarm_driver32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Driver model code abnormal 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver3291 {
            get {
                return ResourceManager.GetString("alarm_driver3291", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Main circuit power supply abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver34 {
            get {
                return ResourceManager.GetString("alarm_driver34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Pre-overload warning 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver35 {
            get {
                return ResourceManager.GetString("alarm_driver35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder initial magnetic field error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver36 {
            get {
                return ResourceManager.GetString("alarm_driver36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder internal error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver37 {
            get {
                return ResourceManager.GetString("alarm_driver37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder internal data reliability error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver38 {
            get {
                return ResourceManager.GetString("alarm_driver38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder internal reset error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver39 {
            get {
                return ResourceManager.GetString("alarm_driver39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Motor matching abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver4 {
            get {
                return ResourceManager.GetString("alarm_driver4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Battery voltage abnormality or encoder internal error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver40 {
            get {
                return ResourceManager.GetString("alarm_driver40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Gray code error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver41 {
            get {
                return ResourceManager.GetString("alarm_driver41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder circle counting error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver42 {
            get {
                return ResourceManager.GetString("alarm_driver42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Motor data abnormal 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver43 {
            get {
                return ResourceManager.GetString("alarm_driver43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Driver overload 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver44 {
            get {
                return ResourceManager.GetString("alarm_driver44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Anti-blocking protection 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver45 {
            get {
                return ResourceManager.GetString("alarm_driver45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Motor Collision Error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver48 {
            get {
                return ResourceManager.GetString("alarm_driver48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Motor power line fault detection 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver49 {
            get {
                return ResourceManager.GetString("alarm_driver49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Regeneration Error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver5 {
            get {
                return ResourceManager.GetString("alarm_driver5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder vibration abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver50 {
            get {
                return ResourceManager.GetString("alarm_driver50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Motor abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver51 {
            get {
                return ResourceManager.GetString("alarm_driver51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder internal communication abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver52 {
            get {
                return ResourceManager.GetString("alarm_driver52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder temperature exceeds protection upper limit 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver53 {
            get {
                return ResourceManager.GetString("alarm_driver53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder abnormal alarm status error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver54 {
            get {
                return ResourceManager.GetString("alarm_driver54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Overload 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver6 {
            get {
                return ResourceManager.GetString("alarm_driver6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_The voltage input of analog speed command is too high 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver66 {
            get {
                return ResourceManager.GetString("alarm_driver66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Driver function usage warning 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver68 {
            get {
                return ResourceManager.GetString("alarm_driver68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Electronic gear ratio setting error 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver69 {
            get {
                return ResourceManager.GetString("alarm_driver69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Speed ​​control error is too large 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver7 {
            get {
                return ResourceManager.GetString("alarm_driver7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Abnormal pulse control command 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver8 {
            get {
                return ResourceManager.GetString("alarm_driver8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Motor parameter abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver83 {
            get {
                return ResourceManager.GetString("alarm_driver83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Motor speed too high 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver86 {
            get {
                return ResourceManager.GetString("alarm_driver86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Emergency Stop_Deceleration 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver863 {
            get {
                return ResourceManager.GetString("alarm_driver863", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Position control error is too large 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver9 {
            get {
                return ResourceManager.GetString("alarm_driver9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Motor position feedback abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver92 {
            get {
                return ResourceManager.GetString("alarm_driver92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_absolute position lost 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver96 {
            get {
                return ResourceManager.GetString("alarm_driver96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Encoder voltage is too low 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver97 {
            get {
                return ResourceManager.GetString("alarm_driver97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Driver_Absolute Position Turns Overflow_Encoder 的當地語系化字串。
        /// </summary>
        internal static string alarm_driver98 {
            get {
                return ResourceManager.GetString("alarm_driver98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Normal 的當地語系化字串。
        /// </summary>
        internal static string alarm_inactive {
            get {
                return ResourceManager.GetString("alarm_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_Servo communication abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_system0 {
            get {
                return ResourceManager.GetString("alarm_system0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_HBM communication abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_system1 {
            get {
                return ResourceManager.GetString("alarm_system1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_E_01 的當地語系化字串。
        /// </summary>
        internal static string alarm_system10 {
            get {
                return ResourceManager.GetString("alarm_system10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_E_02 的當地語系化字串。
        /// </summary>
        internal static string alarm_system11 {
            get {
                return ResourceManager.GetString("alarm_system11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_E_03 的當地語系化字串。
        /// </summary>
        internal static string alarm_system12 {
            get {
                return ResourceManager.GetString("alarm_system12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_E_04 的當地語系化字串。
        /// </summary>
        internal static string alarm_system13 {
            get {
                return ResourceManager.GetString("alarm_system13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_E_05 的當地語系化字串。
        /// </summary>
        internal static string alarm_system14 {
            get {
                return ResourceManager.GetString("alarm_system14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_E_31 的當地語系化字串。
        /// </summary>
        internal static string alarm_system15 {
            get {
                return ResourceManager.GetString("alarm_system15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_Abnormal clean water pressure 的當地語系化字串。
        /// </summary>
        internal static string alarm_system2 {
            get {
                return ResourceManager.GetString("alarm_system2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_Acid pressure abnormal 的當地語系化字串。
        /// </summary>
        internal static string alarm_system3 {
            get {
                return ResourceManager.GetString("alarm_system3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_Buf.A pressure is abnormal 的當地語系化字串。
        /// </summary>
        internal static string alarm_system4 {
            get {
                return ResourceManager.GetString("alarm_system4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Abnormal pressure in System_Buf.B 的當地語系化字串。
        /// </summary>
        internal static string alarm_system5 {
            get {
                return ResourceManager.GetString("alarm_system5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_Abnormal opening and closing of pneumatic cylinder 的當地語系化字串。
        /// </summary>
        internal static string alarm_system6 {
            get {
                return ResourceManager.GetString("alarm_system6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_Windspan optical fiber signal abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_system7 {
            get {
                return ResourceManager.GetString("alarm_system7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_Electrode overwinding abnormality 的當地語系化字串。
        /// </summary>
        internal static string alarm_system8 {
            get {
                return ResourceManager.GetString("alarm_system8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System_E_00 的當地語系化字串。
        /// </summary>
        internal static string alarm_system9 {
            get {
                return ResourceManager.GetString("alarm_system9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Collapse 的當地語系化字串。
        /// </summary>
        internal static string btn_collapse {
            get {
                return ResourceManager.GetString("btn_collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Expand 的當地語系化字串。
        /// </summary>
        internal static string btn_expand {
            get {
                return ResourceManager.GetString("btn_expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go to modify 的當地語系化字串。
        /// </summary>
        internal static string btn_goto_modify {
            get {
                return ResourceManager.GetString("btn_goto_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BUF.A 的當地語系化字串。
        /// </summary>
        internal static string buf_a {
            get {
                return ResourceManager.GetString("buf_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BUF.B 的當地語系化字串。
        /// </summary>
        internal static string buf_b {
            get {
                return ResourceManager.GetString("buf_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Calibration Datalog 的當地語系化字串。
        /// </summary>
        internal static string cal_datalog {
            get {
                return ResourceManager.GetString("cal_datalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear 的當地語系化字串。
        /// </summary>
        internal static string calgrid_clear {
            get {
                return ResourceManager.GetString("calgrid_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Export 的當地語系化字串。
        /// </summary>
        internal static string calgrid_export {
            get {
                return ResourceManager.GetString("calgrid_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File Upload 的當地語系化字串。
        /// </summary>
        internal static string calgrid_upload {
            get {
                return ResourceManager.GetString("calgrid_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cal. Step Setting 的當地語系化字串。
        /// </summary>
        internal static string calibration_step_setting {
            get {
                return ResourceManager.GetString("calibration_step_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Charts 的當地語系化字串。
        /// </summary>
        internal static string charts {
            get {
                return ResourceManager.GetString("charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear Datalog 的當地語系化字串。
        /// </summary>
        internal static string clear_datalog {
            get {
                return ResourceManager.GetString("clear_datalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current Posistion 的當地語系化字串。
        /// </summary>
        internal static string current_position {
            get {
                return ResourceManager.GetString("current_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 D1_Cal.Datalog 的當地語系化字串。
        /// </summary>
        internal static string d1_cal_datalogger {
            get {
                return ResourceManager.GetString("d1_cal_datalogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 D2_Cal.Datalog 的當地語系化字串。
        /// </summary>
        internal static string d2_cal_datalogger {
            get {
                return ResourceManager.GetString("d2_cal_datalogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Alarm Datalog 的當地語系化字串。
        /// </summary>
        internal static string dashboard_alarm_datalog {
            get {
                return ResourceManager.GetString("dashboard_alarm_datalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear 的當地語系化字串。
        /// </summary>
        internal static string dashboard_clear {
            get {
                return ResourceManager.GetString("dashboard_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Electrode endurance 的當地語系化字串。
        /// </summary>
        internal static string dashboard_elec_life {
            get {
                return ResourceManager.GetString("dashboard_elec_life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Endurance 的當地語系化字串。
        /// </summary>
        internal static string dashboard_endurance {
            get {
                return ResourceManager.GetString("dashboard_endurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Real Time Trend Chart of Measurement 的當地語系化字串。
        /// </summary>
        internal static string dashboard_pH_live_chart {
            get {
                return ResourceManager.GetString("dashboard_pH_live_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remaining days 的當地語系化字串。
        /// </summary>
        internal static string dashboard_remaindays {
            get {
                return ResourceManager.GetString("dashboard_remaindays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Electrode #1 的當地語系化字串。
        /// </summary>
        internal static string dialog_electrode1 {
            get {
                return ResourceManager.GetString("dialog_electrode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Electrode #2 的當地語系化字串。
        /// </summary>
        internal static string dialog_electrode2 {
            get {
                return ResourceManager.GetString("dialog_electrode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please replace the electrode as soon as possible. 的當地語系化字串。
        /// </summary>
        internal static string dialog_maintain30 {
            get {
                return ResourceManager.GetString("dialog_maintain30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please contact the relevant engineer to check if the electrode KCL is sufficient. 的當地語系化字串。
        /// </summary>
        internal static string dialog_maintain60 {
            get {
                return ResourceManager.GetString("dialog_maintain60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Condition is acceptable. Please check if the standard solution measurement is sufficient and correct. 的當地語系化字串。
        /// </summary>
        internal static string dialog_maintain70 {
            get {
                return ResourceManager.GetString("dialog_maintain70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Condition is good. Please check if the electrode position in the calibration tank is misaligned. 的當地語系化字串。
        /// </summary>
        internal static string dialog_maintain80 {
            get {
                return ResourceManager.GetString("dialog_maintain80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Export Datalog 的當地語系化字串。
        /// </summary>
        internal static string export_datalog {
            get {
                return ResourceManager.GetString("export_datalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AW 的當地語系化字串。
        /// </summary>
        internal static string field_aw {
            get {
                return ResourceManager.GetString("field_aw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Biology 的當地語系化字串。
        /// </summary>
        internal static string field_bio {
            get {
                return ResourceManager.GetString("field_bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cu_CMP 的當地語系化字串。
        /// </summary>
        internal static string field_cmp {
            get {
                return ResourceManager.GetString("field_cmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CMP 的當地語系化字串。
        /// </summary>
        internal static string field_cucmp {
            get {
                return ResourceManager.GetString("field_cucmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HF 的當地語系化字串。
        /// </summary>
        internal static string field_hf {
            get {
                return ResourceManager.GetString("field_hf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LSR 的當地語系化字串。
        /// </summary>
        internal static string field_lsr {
            get {
                return ResourceManager.GetString("field_lsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NH 的當地語系化字串。
        /// </summary>
        internal static string field_nh {
            get {
                return ResourceManager.GetString("field_nh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pure Water 的當地語系化字串。
        /// </summary>
        internal static string field_pure {
            get {
                return ResourceManager.GetString("field_pure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Field Selection 的當地語系化字串。
        /// </summary>
        internal static string field_selection {
            get {
                return ResourceManager.GetString("field_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 History Chart 的當地語系化字串。
        /// </summary>
        internal static string history_chart {
            get {
                return ResourceManager.GetString("history_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End Date 的當地語系化字串。
        /// </summary>
        internal static string history_end_date {
            get {
                return ResourceManager.GetString("history_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start Date 的當地語系化字串。
        /// </summary>
        internal static string history_start_date {
            get {
                return ResourceManager.GetString("history_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Home 的當地語系化字串。
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Click the expand button to change the password 的當地語系化字串。
        /// </summary>
        internal static string lab_change_password {
            get {
                return ResourceManager.GetString("lab_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language Selection 的當地語系化字串。
        /// </summary>
        internal static string language_selection {
            get {
                return ResourceManager.GetString("language_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Live Chart 的當地語系化字串。
        /// </summary>
        internal static string live_chart {
            get {
                return ResourceManager.GetString("live_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please check your email for the verification code and enter it to verify. 的當地語系化字串。
        /// </summary>
        internal static string message_check_email {
            get {
                return ResourceManager.GetString("message_check_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter the email. 的當地語系化字串。
        /// </summary>
        internal static string message_enter_email {
            get {
                return ResourceManager.GetString("message_enter_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        internal static string message_error {
            get {
                return ResourceManager.GetString("message_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password change failed 的當地語系化字串。
        /// </summary>
        internal static string message_password_change_failed {
            get {
                return ResourceManager.GetString("message_password_change_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The password has been changed 的當地語系化字串。
        /// </summary>
        internal static string message_password_changed {
            get {
                return ResourceManager.GetString("message_password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Success 的當地語系化字串。
        /// </summary>
        internal static string message_success {
            get {
                return ResourceManager.GetString("message_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The verification code is invalid. 的當地語系化字串。
        /// </summary>
        internal static string message_verification_code_invalid {
            get {
                return ResourceManager.GetString("message_verification_code_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A.Cal 的當地語系化字串。
        /// </summary>
        internal static string modal_a_cal {
            get {
                return ResourceManager.GetString("modal_a_cal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A.Wash 的當地語系化字串。
        /// </summary>
        internal static string modal_a_wash {
            get {
                return ResourceManager.GetString("modal_a_wash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back to original 的當地語系化字串。
        /// </summary>
        internal static string modal_back_to_original {
            get {
                return ResourceManager.GetString("modal_back_to_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string modal_cancel {
            get {
                return ResourceManager.GetString("modal_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        internal static string modal_close {
            get {
                return ResourceManager.GetString("modal_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm 的當地語系化字串。
        /// </summary>
        internal static string modal_confirm {
            get {
                return ResourceManager.GetString("modal_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cylinder 的當地語系化字串。
        /// </summary>
        internal static string modal_cylinder {
            get {
                return ResourceManager.GetString("modal_cylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        internal static string modal_delete {
            get {
                return ResourceManager.GetString("modal_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select a language 的當地語系化字串。
        /// </summary>
        internal static string modal_ent_select_language {
            get {
                return ResourceManager.GetString("modal_ent_select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        internal static string modal_language {
            get {
                return ResourceManager.GetString("modal_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 M.BufA 的當地語系化字串。
        /// </summary>
        internal static string modal_m_bufa {
            get {
                return ResourceManager.GetString("modal_m_bufa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 M.BufB 的當地語系化字串。
        /// </summary>
        internal static string modal_m_bufb {
            get {
                return ResourceManager.GetString("modal_m_bufb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 M.REAG 的當地語系化字串。
        /// </summary>
        internal static string modal_m_reag {
            get {
                return ResourceManager.GetString("modal_m_reag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 M.Wash 的當地語系化字串。
        /// </summary>
        internal static string modal_m_wash {
            get {
                return ResourceManager.GetString("modal_m_wash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stop 的當地語系化字串。
        /// </summary>
        internal static string modal_stop {
            get {
                return ResourceManager.GetString("modal_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hoister Unlock 的當地語系化字串。
        /// </summary>
        internal static string modal_unlock {
            get {
                return ResourceManager.GetString("modal_unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IP address configuration 的當地語系化字串。
        /// </summary>
        internal static string nav_ip_url {
            get {
                return ResourceManager.GetString("nav_ip_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Proccess Setting 的當地語系化字串。
        /// </summary>
        internal static string proccess_setting {
            get {
                return ResourceManager.GetString("proccess_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 REAG. 的當地語系化字串。
        /// </summary>
        internal static string reag {
            get {
                return ResourceManager.GetString("reag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Schedule 的當地語系化字串。
        /// </summary>
        internal static string schedule {
            get {
                return ResourceManager.GetString("schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Calibration 的當地語系化字串。
        /// </summary>
        internal static string schedule_calibration {
            get {
                return ResourceManager.GetString("schedule_calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Daily 的當地語系化字串。
        /// </summary>
        internal static string schedule_daily {
            get {
                return ResourceManager.GetString("schedule_daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Description 的當地語系化字串。
        /// </summary>
        internal static string schedule_description {
            get {
                return ResourceManager.GetString("schedule_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End Time 的當地語系化字串。
        /// </summary>
        internal static string schedule_end_time {
            get {
                return ResourceManager.GetString("schedule_end_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select a subject 的當地語系化字串。
        /// </summary>
        internal static string schedule_ent_select_subject {
            get {
                return ResourceManager.GetString("schedule_ent_select_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select a system 的當地語系化字串。
        /// </summary>
        internal static string schedule_ent_select_system {
            get {
                return ResourceManager.GetString("schedule_ent_select_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Export 的當地語系化字串。
        /// </summary>
        internal static string schedule_export {
            get {
                return ResourceManager.GetString("schedule_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Frequency 的當地語系化字串。
        /// </summary>
        internal static string schedule_frequency {
            get {
                return ResourceManager.GetString("schedule_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Event Setting 的當地語系化字串。
        /// </summary>
        internal static string schedule_modal_title {
            get {
                return ResourceManager.GetString("schedule_modal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Monthly 的當地語系化字串。
        /// </summary>
        internal static string schedule_monthly {
            get {
                return ResourceManager.GetString("schedule_monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start Time 的當地語系化字串。
        /// </summary>
        internal static string schedule_start_time {
            get {
                return ResourceManager.GetString("schedule_start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Subject 的當地語系化字串。
        /// </summary>
        internal static string schedule_subject {
            get {
                return ResourceManager.GetString("schedule_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System 的當地語系化字串。
        /// </summary>
        internal static string schedule_system {
            get {
                return ResourceManager.GetString("schedule_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wash 的當地語系化字串。
        /// </summary>
        internal static string schedule_wash {
            get {
                return ResourceManager.GetString("schedule_wash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Weekly 的當地語系化字串。
        /// </summary>
        internal static string schedule_weekly {
            get {
                return ResourceManager.GetString("schedule_weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Step and Set Time 的當地語系化字串。
        /// </summary>
        internal static string select_step_and_set_time {
            get {
                return ResourceManager.GetString("select_step_and_set_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Total Steps 的當地語系化字串。
        /// </summary>
        internal static string select_total_steps {
            get {
                return ResourceManager.GetString("select_total_steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Set Cleaning Content 的當地語系化字串。
        /// </summary>
        internal static string set_cleaning_content {
            get {
                return ResourceManager.GetString("set_cleaning_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Position Setting 的當地語系化字串。
        /// </summary>
        internal static string set_position {
            get {
                return ResourceManager.GetString("set_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show history alarm 的當地語系化字串。
        /// </summary>
        internal static string show_history_alarm {
            get {
                return ResourceManager.GetString("show_history_alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show InAlarm 的當地語系化字串。
        /// </summary>
        internal static string show_inalarm {
            get {
                return ResourceManager.GetString("show_inalarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Step 的當地語系化字串。
        /// </summary>
        internal static string step {
            get {
                return ResourceManager.GetString("step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Step 的當地語系化字串。
        /// </summary>
        internal static string step_number {
            get {
                return ResourceManager.GetString("step_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Step Setting 的當地語系化字串。
        /// </summary>
        internal static string step_number_setting {
            get {
                return ResourceManager.GetString("step_number_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto 的當地語系化字串。
        /// </summary>
        internal static string system_auto {
            get {
                return ResourceManager.GetString("system_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manual 的當地語系化字串。
        /// </summary>
        internal static string system_manual {
            get {
                return ResourceManager.GetString("system_manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total Steps 的當地語系化字串。
        /// </summary>
        internal static string total_steps {
            get {
                return ResourceManager.GetString("total_steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Trendline Generation 的當地語系化字串。
        /// </summary>
        internal static string trendline_generation {
            get {
                return ResourceManager.GetString("trendline_generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wash 的當地語系化字串。
        /// </summary>
        internal static string wash {
            get {
                return ResourceManager.GetString("wash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Washing Step Setting 的當地語系化字串。
        /// </summary>
        internal static string washing_step_setting {
            get {
                return ResourceManager.GetString("washing_step_setting", resourceCulture);
            }
        }
    }
}
